expectedScan = [ { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 7,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 9,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 13,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 21,
    name: 'ftp',
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 22,
    name: 'ssh',
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 23,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 25,
    name: 'smtp',
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 26,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 37,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 53,
    name: 'domain',
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 79,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 80,
    name: 'http',
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'open',
    syn_reason: 'syn-ack',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 81,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 88,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 106,
    name: 'pop3pw',
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 110,
    name: 'pop3',
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 111,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 113,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 119,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 135,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 139,
    name: 'netbios-ssn',
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 143,
    name: 'imap',
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 144,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 179,
    name: 'bgp',
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 199,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 389,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 427,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 443,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 444,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 445,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 465,
    name: 'smtps',
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 513,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 514,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 515,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 543,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 544,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 548,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 554,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 587,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 631,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 646,
    name: 'ldp',
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 873,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 990,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 993,
    name: 'imaps',
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 995,
    name: 'pop3s',
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 1025,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 1026,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 1027,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 1028,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 1029,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 1110,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 1433,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 1720,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 1723,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 1755,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 1900,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 2000,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 2001,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 2049,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 2121,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 2717,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 3000,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 3128,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 3306,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 3389,
    name: 'ms-wbt-server',
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'open',
    syn_reason: 'syn-ack',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 3986,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 4899,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 5000,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 5009,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 5051,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 5060,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 5101,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 5190,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 5357,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 5432,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 5631,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 5666,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 5800,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 5900,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 6000,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 6001,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 6646,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 7070,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 8000,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 8008,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 8009,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 8080,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 8081,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 8443,
    name: 'https-alt',
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 8888,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 9100,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 9999,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 10000,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 32768,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 49152,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 49153,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 49154,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 49155,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 49156,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' },
  { hostname: 'testhtml5.vulnweb.com',
    protocol: 'tcp',
    port: 49157,
    name: null,
    ack_state: 'filtered',
    ack_reason: 'no-responses',
    ack_completed_time: 'Tue Oct  3 21:32:11 2017',
    null_state: 'open|filtered',
    null_reason: 'no-responses',
    null_completed_time: 'Tue Oct  3 21:27:49 2017',
    syn_state: 'filtered',
    syn_reason: 'no-responses',
    syn_completed_time: 'Tue Oct  3 21:20:46 2017',
    xmas_state: 'open|filtered',
    xmas_reason: 'no-responses',
    xmas_completed_time: 'Tue Oct  3 21:10:34 2017' } ]

module.exports.expectedScan = expectedScan;
